In [2]:
%load_ext watermark

In [3]:
%watermark

Last updated: 2022-11-22T10:48:13.748455-05:00

Python implementation: CPython
Python version       : 3.7.11
IPython version      : 7.10.1

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 4.15.0-161-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 40
Architecture: 64bit



In [4]:
import numpy as np
import pandas as pd

In [5]:
%watermark --iversions

pandas: 1.3.5
numpy : 1.19.2



In [6]:
X_num_train = np.load('../input/higgs_small_roc/X_num_train.npy')
X_num_val = np.load('../input/higgs_small_roc/X_num_val.npy')
X_num_test = np.load('../input/higgs_small_roc/X_num_test.npy')

y_train = np.load('../input/higgs_small_roc/y_train.npy')
y_val = np.load('../input/higgs_small_roc/y_val.npy')
y_test = np.load('../input/higgs_small_roc/y_test.npy')

In [7]:
X_num_train.shape

(62751, 28)

In [8]:
X_num_train.size

1757028

In [11]:
index_nan = np.random.choice(X_num_train.size, X_num_train.shape[0]*2, replace=False)
index_nan

array([1414611,  654367, 1711713, ...,  820382,  363316,  745408])

In [12]:
trains = []
for i in range(5):
    trains.append(X_num_train)

In [13]:
X_num_train_5 = np.vstack(trains)

In [14]:
X_num_train_5.shape

(313755, 28)

In [15]:
index_nan = np.random.choice(X_num_train_5.size, X_num_train_5.shape[0]*2, replace=False)
index_nan

array([7395956, 8355326,   47831, ...,  998976, 5750957, 4188573])

In [16]:
X_num_train_5.ravel()[index_nan] = np.nan

In [26]:
X_num_train_5[8]

array([ 0.7267291 ,         nan,         nan,  0.80474496,         nan,
        0.82492304, -0.7922094 , -1.4801266 ,  2.1730762 ,  0.5755049 ,
       -0.03588055,  0.88429826,  2.2148721 ,  0.7528887 , -1.0830232 ,
        0.59291756,  0.        ,  1.1092063 , -1.6869278 ,  0.2595374 ,
        0.        ,  0.5264462 ,  1.1162164 ,  1.0526779 ,  0.78055453,
        0.9455386 ,  0.79644614,  0.70450157], dtype=float32)

In [27]:
columns = [f'Col{i}' for i in range(28)]

In [28]:
X_num_train_5 = pd.DataFrame(X_num_train_5, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [29]:
y_train_5 = []
for i in range(5):
    y_train_5.append(y_train)

In [32]:
y_train_5 = np.hstack(y_train_5)

In [34]:
X_num_train_5.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  2.118879 -0.047779  0.422666  0.887075  1.190011  1.125486  0.433695   
1  0.597891  1.086895  0.923151  0.226966       NaN  0.797166  0.150490   
2  0.745762 -1.198036 -0.740429  1.239304  0.256762       NaN -0.103009   
3  0.754730  1.291428  0.714523  0.850122  0.253473  0.934852 -0.733786   
4  1.336332 -0.407173  1.026355  2.019245  0.558858  1.559704 -0.726854   

       Col7      Col8      Col9  ...     Col19     Col20     Col21     Col22  \
0 -1.338761  0.000000       NaN  ... -1.553466  0.000000  0.742982  0.823960   
1 -0.124122  1.086538  1.316699  ... -1.554576  0.000000  0.847783  0.790057   
2  1.449852  2.173076  0.923754  ... -1.242160  0.000000  0.803592  0.958226   
3  1.407166       NaN  0.883717  ... -0.825421  0.000000  2.054786  1.577448   
4       NaN  0.000000  0.810315  ...  1.100229  3.101961  0.922455  0.879696   

      Col23     Col24     Col25     Col26     Col27  target  
0  1.211727  0.916147       NaN  0.654138  0.825789       0  
1  0.983838  1.056745  1.567410  0.940275  0.807826       1  
2  1.042696  0.962325  0.753004  0.781717  0.711513       1  
3  0.999547  2.386760  1.455588  1.757753  1.538811       0  
4  0.983609  0.971203  1.022390  1.006686  1.130976       0  

[5 rows x 29 columns]

In [ ]:
X_num_train_5['target'] = y_train_5
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [35]:
X_num_train_5 = X_num_train_5.sample(frac=1).reset_index(drop=True)
X_num_train_5.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  1.036929  1.006056  1.200027  0.454295 -1.117098       NaN  1.233801   
1  1.047544 -0.712999  0.062561  1.428549  0.688818  0.721315 -1.170477   
2  0.936275 -1.703525 -0.577299  1.001859  0.871798  0.655816 -1.412093   
3  0.696167 -0.463663 -0.658309  0.675300  1.132573  0.840679  0.499050   
4  0.596427  1.417071 -1.251456  1.092743  1.628276  0.982579 -0.162423   

       Col7      Col8      Col9  ...     Col19     Col20     Col21     Col22  \
0 -0.254400  2.173076  0.703801  ... -1.349813  3.101961  1.015689  1.134209   
1 -0.922425  0.000000       NaN  ...  1.405431  1.550981  0.844791  0.923488   
2  0.269587  2.173076  0.892908  ...  0.422127  0.000000  0.816192  1.095531   
3  0.495218  2.173076  1.247074  ...  1.071374  0.000000  1.210503  0.853027   
4  0.373255  0.000000       NaN  ...  0.620785  0.000000  0.847467  0.887198   

      Col23     Col24     Col25     Col26     Col27  target  
0  0.987833  0.577949  0.881929       NaN  0.723618       1  
1  0.991520  0.887377       NaN  0.712471  0.712422       0  
2  1.295066  0.783746  0.871041  0.923142  0.840195       1  
3  0.988402  0.963329  0.761007  0.785013       NaN       1  
4  0.996937  1.759708  0.579911  1.134156  1.408581       0  

[5 rows x 29 columns]

In [36]:
X_num_train_5 = X_num_train_5.sample(frac=1).reset_index(drop=True)
X_num_train_5.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  0.336554       NaN -1.034505  2.136067  1.091630  0.825747 -0.228769   
1  0.516269 -1.261344 -1.145478  1.446142 -0.372901  0.645922 -0.557525   
2  0.411038  0.301876  0.824940  1.426709 -0.961902  1.082889  0.600054   
3  0.381757 -0.107191  1.440837  1.568934 -0.289028  1.317495  0.531728   
4  1.397091 -0.829876  0.923151  0.252031 -1.126705  0.976991 -0.040625   

       Col7      Col8      Col9  ...     Col19  Col20     Col21     Col22  \
0 -0.582593  0.000000  0.542392  ...  0.241225    NaN  0.857981  0.907894   
1  1.326227  0.000000       NaN  ... -1.567894    0.0  0.721187  0.868237   
2  1.534672  2.173076  1.186514  ...  0.677941    0.0  1.053019       NaN   
3 -0.903022  2.173076  1.207792  ...  0.789478    0.0  0.345580  0.882028   
4 -0.810441  2.173076  0.436004  ...  1.444830    0.0  0.982152  0.860474   

      Col23     Col24     Col25     Col26     Col27  target  
0  1.105223  0.733101  0.449465  0.660714  0.842115       0  
1  0.987552  0.497126  0.778771  0.676624  0.729427       0  
2  1.060117  0.974307  1.836427  1.193518  1.026776       1  
3  1.072079  0.996085  1.824473  1.113359  0.960487       1  
4  0.991044  1.210401  0.834887  0.836636  0.787843       0  

[5 rows x 29 columns]

In [37]:
X_num_train_5.to_csv('../input/higgs_small_roc/xgtrain_5.csv', index=False)
X_num_val.to_csv('../input/higgs_small_roc/xgval.csv', index=False)
X_num_test.to_csv('../input/higgs_small_roc/xgtest.csv', index=False)