In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2022-11-22T18:35:24.842725-05:00

Python implementation: CPython
Python version       : 3.7.11
IPython version      : 7.10.1

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 4.15.0-161-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 40
Architecture: 64bit



In [3]:
import numpy as np
import pandas as pd

In [4]:
%watermark --iversions

pandas: 1.3.5
numpy : 1.19.2



In [5]:
X_num_train = np.load('../input/higgs_small_roc/X_num_train.npy')
X_num_val = np.load('../input/higgs_small_roc/X_num_val.npy')
X_num_test = np.load('../input/higgs_small_roc/X_num_test.npy')

y_train = np.load('../input/higgs_small_roc/y_train.npy')
y_val = np.load('../input/higgs_small_roc/y_val.npy')
y_test = np.load('../input/higgs_small_roc/y_test.npy')

In [6]:
X_num_train.shape

(62751, 28)

In [7]:
X_num_train.size

1757028

In [8]:
index_nan = np.random.choice(X_num_train.size, X_num_train.shape[0]*3, replace=False)
index_nan

array([ 191089,  429829,  836125, ..., 1347092,   57740, 1029336])

In [9]:
trains = []
for i in range(25):
    trains.append(X_num_train)

In [10]:
X_num_train_25 = np.vstack(trains)

In [11]:
X_num_train_25.shape

(1568775, 28)

In [12]:
index_nan = np.random.choice(X_num_train_25.size, X_num_train_25.shape[0]*3, replace=False)
index_nan

array([23773715, 17854431, 34655554, ..., 38320321,  4377295,  2514287])

In [13]:
X_num_train_25.ravel()[index_nan] = np.nan

In [14]:
X_num_train_25[8]

array([ 0.7267291 ,         nan, -0.8125607 ,  0.80474496,  1.0561434 ,
        0.82492304, -0.7922094 , -1.4801266 ,  2.1730762 ,  0.5755049 ,
       -0.03588055,         nan,         nan,  0.7528887 , -1.0830232 ,
        0.59291756,  0.        ,  1.1092063 , -1.6869278 ,  0.2595374 ,
        0.        ,  0.5264462 ,  1.1162164 ,  1.0526779 ,  0.78055453,
        0.9455386 ,  0.79644614,  0.70450157], dtype=float32)

In [15]:
columns = [f'Col{i}' for i in range(28)]

In [16]:
X_num_train_25 = pd.DataFrame(X_num_train_25, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [17]:
y_train_25 = []
for i in range(25):
    y_train_25.append(y_train)

In [18]:
y_train_25 = np.hstack(y_train_25)

In [19]:
X_num_train_25.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  2.118879 -0.047779  0.422666  0.887075  1.190011  1.125486  0.433695   
1  0.597891  1.086895  0.923151  0.226966  0.371219  0.797166  0.150490   
2  0.745762 -1.198036 -0.740429  1.239304  0.256762  0.490740 -0.103009   
3  0.754730  1.291428       NaN  0.850122  0.253473  0.934852 -0.733786   
4  1.336332 -0.407173  1.026355  2.019245  0.558858  1.559704 -0.726854   

       Col7      Col8      Col9  ...     Col18     Col19     Col20     Col21  \
0 -1.338761       NaN  0.439529  ...       NaN -1.553466  0.000000  0.742982   
1 -0.124122       NaN  1.316699  ...  0.799050 -1.554576  0.000000  0.847783   
2  1.449852  2.173076  0.923754  ...  1.765957 -1.242160       NaN  0.803592   
3  1.407166  2.173076  0.883717  ...       NaN -0.825421  0.000000  2.054786   
4 -1.027756  0.000000  0.810315  ...  0.766570  1.100229  3.101961  0.922455   

      Col22     Col23     Col24     Col25     Col26     Col27  
0  0.823960  1.211727  0.916147  0.578919  0.654138  0.825789  
1       NaN       NaN  1.056745  1.567410  0.940275  0.807826  
2       NaN  1.042696  0.962325  0.753004  0.781717  0.711513  
3  1.577448  0.999547  2.386760  1.455588  1.757753  1.538811  
4  0.879696  0.983609  0.971203  1.022390  1.006686  1.130976  

[5 rows x 28 columns]

In [20]:
X_num_train_25['target'] = y_train_25
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [21]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  0.578492       NaN  0.169649  1.137164  1.346456  0.706383 -0.781317   
1  1.308881       NaN  0.660702  0.216433  0.221429  1.664503  0.351506   
2  2.324764  0.562900 -1.455645  0.457724  0.035080  2.124005       NaN   
3  0.362175       NaN  1.071854  2.654360  0.479483  1.424859 -0.866477   
4  0.808168  1.560244 -1.694235  0.832291  0.317696  0.973968  0.834738   

       Col7      Col8      Col9  ...     Col19     Col20     Col21     Col22  \
0 -0.997266  2.173076  0.711103  ...  1.602425  0.000000       NaN  0.823432   
1 -1.518379  0.000000       NaN  ... -0.560173  3.101961  0.865910  0.998969   
2       NaN  2.173076       NaN  ... -0.012472       NaN  1.150136  0.943345   
3 -1.276671  2.173076  0.730996  ...  0.796692  0.000000  1.049395  0.851536   
4  0.083317  2.173076  1.203637  ...       NaN  0.000000  0.421167  0.789350   

      Col23     Col24     Col25     Col26     Col27  target  
0  0.987815  0.740955  1.060955  0.863233       NaN       0  
1  0.996867  0.713393  1.303954  1.285414  1.088218       0  
2  1.392562  2.057497  1.632758  1.432589  1.304788       1  
3  0.978458       NaN  0.717230  1.656526  1.411692       1  
4       NaN  1.880767  2.320791  1.477240  1.112820       0  

[5 rows x 29 columns]

In [22]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  0.392188 -0.476325 -0.419161  1.380128  0.104439  0.248897 -0.345616   
1  0.435928       NaN  0.800527  1.151687       NaN  1.162679       NaN   
2  1.996812  1.271949 -0.009674  1.744268       NaN  0.861108  1.469476   
3  1.622742 -1.190244 -0.927417  2.146134       NaN  1.187504  0.504992   
4  0.556897  0.877492  1.206685  0.523024 -1.085213  2.270210 -1.047689   

       Col7      Col8      Col9  ...     Col19  Col20     Col21     Col22  \
0  1.281877  2.173076  1.020826  ... -1.577327    0.0  0.577486  1.203902   
1 -1.483453  2.173076  1.382546  ... -0.778254    0.0  0.743372  1.156230   
2 -1.484562  1.086538  0.492912  ...  1.324414    0.0  0.483322  0.498010   
3  0.969209  1.086538       NaN  ...  0.155214    0.0  0.898371  1.250772   
4  1.393860  0.000000  2.880043  ... -1.546252    0.0  1.484622  1.526148   

      Col23     Col24     Col25     Col26     Col27  target  
0  0.993673  0.785857  0.627040  0.917488  0.820388       1  
1       NaN  1.073451  0.959847  1.777208  1.359101       1  
2  1.068540  1.111729  0.883074  1.041028  0.844712       1  
3  1.081083  1.499588  0.632972  1.631003  1.570494       0  
4  0.990836  2.552061  0.808916  1.739306  1.975971       1  

[5 rows x 29 columns]

In [23]:
X_num_train_25.to_csv('../input/higgs_small_roc/xgtrain_25_3.csv', index=False)
X_num_val.to_csv('../input/higgs_small_roc/xgval.csv', index=False)
X_num_test.to_csv('../input/higgs_small_roc/xgtest.csv', index=False)