In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2022-11-23T08:54:23.856943-05:00

Python implementation: CPython
Python version       : 3.7.11
IPython version      : 7.10.1

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 4.15.0-161-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 40
Architecture: 64bit



In [3]:
import numpy as np
import pandas as pd

In [4]:
%watermark --iversions

pandas: 1.3.5
numpy : 1.19.2



In [5]:
X_num_train = np.load('../input/higgs_small_roc/X_num_train.npy')
X_num_val = np.load('../input/higgs_small_roc/X_num_val.npy')
X_num_test = np.load('../input/higgs_small_roc/X_num_test.npy')

y_train = np.load('../input/higgs_small_roc/y_train.npy')
y_val = np.load('../input/higgs_small_roc/y_val.npy')
y_test = np.load('../input/higgs_small_roc/y_test.npy')

In [6]:
X_num_train.shape

(62751, 28)

In [7]:
X_num_train.size

1757028

In [8]:
index_nan = np.random.choice(X_num_train.size, X_num_train.shape[0]*1, replace=False)
index_nan

array([ 774434, 1239938, 1273853, ...,  614945, 1472188,  949556])

In [9]:
trains = []
for i in range(25):
    trains.append(X_num_train)

In [10]:
X_num_train_25 = np.vstack(trains)

In [11]:
X_num_train_25.shape

(1568775, 28)

In [12]:
index_nan = np.random.choice(X_num_train_25.size, X_num_train_25.shape[0]*1, replace=False)
index_nan

array([ 1578342, 26999917,  8074739, ..., 21608445, 23396313, 41304993])

In [13]:
X_num_train_25.ravel()[index_nan] = np.nan

In [14]:
X_num_train_25[8]

array([ 0.7267291 , -1.3421831 , -0.8125607 ,  0.80474496,  1.0561434 ,
        0.82492304, -0.7922094 , -1.4801266 ,  2.1730762 ,  0.5755049 ,
       -0.03588055,  0.88429826,  2.2148721 ,  0.7528887 , -1.0830232 ,
        0.59291756,         nan,  1.1092063 , -1.6869278 ,  0.2595374 ,
        0.        ,  0.5264462 ,  1.1162164 ,  1.0526779 ,  0.78055453,
        0.9455386 ,  0.79644614,  0.70450157], dtype=float32)

In [15]:
columns = [f'Col{i}' for i in range(28)]

In [16]:
X_num_train_25 = pd.DataFrame(X_num_train_25, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [17]:
y_train_25 = []
for i in range(25):
    y_train_25.append(y_train)

In [18]:
y_train_25 = np.hstack(y_train_25)

In [19]:
X_num_train_25.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  2.118879 -0.047779  0.422666  0.887075  1.190011  1.125486  0.433695   
1  0.597891  1.086895  0.923151  0.226966  0.371219  0.797166  0.150490   
2  0.745762 -1.198036 -0.740429  1.239304  0.256762  0.490740 -0.103009   
3  0.754730  1.291428  0.714523       NaN  0.253473  0.934852 -0.733786   
4  1.336332 -0.407173  1.026355  2.019245  0.558858  1.559704 -0.726854   

       Col7      Col8      Col9  ...     Col18     Col19     Col20     Col21  \
0 -1.338761  0.000000  0.439529  ... -0.323596 -1.553466  0.000000  0.742982   
1 -0.124122  1.086538  1.316699  ...  0.799050 -1.554576  0.000000  0.847783   
2  1.449852  2.173076  0.923754  ...  1.765957 -1.242160  0.000000  0.803592   
3  1.407166  2.173076  0.883717  ...  1.262099 -0.825421  0.000000  2.054786   
4 -1.027756  0.000000  0.810315  ...  0.766570  1.100229  3.101961  0.922455   

      Col22     Col23     Col24     Col25     Col26     Col27  
0  0.823960  1.211727  0.916147  0.578919  0.654138  0.825789  
1  0.790057  0.983838  1.056745  1.567410  0.940275  0.807826  
2  0.958226  1.042696  0.962325  0.753004  0.781717  0.711513  
3  1.577448  0.999547  2.386760  1.455588  1.757753  1.538811  
4  0.879696  0.983609  0.971203  1.022390  1.006686  1.130976  

[5 rows x 28 columns]

In [20]:
X_num_train_25['target'] = y_train_25
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [21]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  1.521538  0.868726  0.065890  1.913573 -0.164498  0.691451  1.112003   
1  1.645069  0.422648 -0.960709  0.990600  1.722206  0.805960 -0.708040   
2  0.652610 -1.825271  1.650019  0.479689 -0.814242  0.933386 -1.198204   
3  0.698729 -1.206801  0.760577  0.893693  0.428602  0.729743  0.040574   
4       NaN -1.336339  0.185185  0.879533 -1.397903  1.204910 -0.048547   

       Col7      Col8      Col9  ...     Col19     Col20     Col21     Col22  \
0  1.197612  0.000000  0.508272  ...  1.428182  0.000000  0.993843  0.972384   
1  0.011248  2.173076  1.052301  ...  1.614633  0.000000  0.916381  1.012631   
2 -0.317044  0.000000  0.299399  ...  1.409870  3.101961  0.974951  0.984349   
3 -1.231212  2.173076       NaN  ...  0.034798  0.000000  0.743899  0.870864   
4 -0.683489  2.173076  1.136909  ...  0.547537  3.101961  1.060595  0.864659   

      Col23     Col24     Col25     Col26     Col27  target  
0  0.982740  1.268167  0.762958  0.887896  0.953018       1  
1  1.171068  1.206123  1.011313  1.072842  0.895347       1  
2  0.995891  0.618927  0.350304  0.695416  0.639008       1  
3  0.982310  0.749382  0.604286  0.736275  0.718284       0  
4  0.987117  0.886045  1.154138  1.173581  0.936603       0  

[5 rows x 29 columns]

In [22]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

Col0      Col1      Col2      Col3      Col4      Col5      Col6  \
0  0.942131  1.897237 -0.410838  1.208800  0.618111  0.773989  0.104939   
1  0.546465  0.679776 -1.326917  1.833739  0.259129  0.860925 -0.111921   
2  0.949268 -0.456846  0.110279       NaN  1.445008  1.170649 -0.316899   
3  1.168696 -0.960387  0.644056  1.668392  0.903572  1.639952 -0.894203   
4  0.499249  1.289481 -0.978464  0.788959  0.565607  0.669466 -0.527818   

       Col7      Col8      Col9  ...     Col19     Col20     Col21     Col22  \
0 -1.721834  2.173076  0.787778  ...  0.534219  0.000000  0.859762  0.952683   
1 -0.497216  0.000000  1.459977  ... -1.526275  0.000000  1.556438  1.039222   
2  1.506953  0.000000  1.642789  ...  1.342171  0.000000  0.645799  0.649397   
3 -1.452962  2.173076  1.190795  ...  0.260647  0.000000  0.976780  2.543204   
4       NaN  0.000000  1.000051  ... -1.687199  3.101961  1.008931  0.926738   

      Col23     Col24     Col25     Col26     Col27  target  
0  1.183130  1.517570  0.823106  1.280084  1.002378       1  
1  1.373045  1.160709  0.714822  0.942559  0.888690       1  
2  1.220441  1.104470  0.334128  0.922434  0.827273       0  
3  0.992699  1.698556  1.149998  2.191567  1.840188       1  
4  0.986293  1.303238  1.018709  0.912322  0.865946       0  

[5 rows x 29 columns]

In [23]:
X_num_train_25.to_csv('../input/higgs_small_roc/xgtrain_25_1.csv', index=False)
X_num_val.to_csv('../input/higgs_small_roc/xgval.csv', index=False)
X_num_test.to_csv('../input/higgs_small_roc/xgtest.csv', index=False)