In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2022-12-08T14:56:24.474766-05:00

Python implementation: CPython
Python version       : 3.8.9
IPython version      : 8.4.0

Compiler    : Clang 13.1.6 (clang-1316.0.21.2.5)
OS          : Darwin
Release     : 21.5.0
Machine     : arm64
Processor   : arm
CPU cores   : 20
Architecture: 64bit



In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

In [4]:
%watermark --iversions

numpy : 1.23.4
pandas: 1.5.1



In [6]:
X_num_train = np.load('../input/otto_ii/X_num_train.npy')
X_num_val = np.load('../input/otto_ii/X_num_val.npy')
X_num_test = np.load('../input/otto_ii/X_num_test.npy')

y_train = np.load('../input/otto_ii/y_train.npy')
y_val = np.load('../input/otto_ii/y_val.npy')
y_test = np.load('../input/otto_ii/y_test.npy')

In [7]:
X_num_train.shape

(39601, 93)

In [10]:
y_train

array([8, 1, 1, ..., 7, 2, 1])

In [11]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
clf = LogisticRegression()

In [13]:
clf.fit(X_num_train, y_train)

/Users/tunguz/Library/Python/3.8/lib/python/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
val_preds = clf.predict_proba(X_num_val)
test_preds = clf.predict_proba(X_num_test)

In [15]:
val_preds

array([[1.13170163e-03, 1.73097758e-09, 5.74337410e-10, ...,
        7.04057587e-04, 9.93980431e-01, 3.08565859e-07],
       [9.63724946e-03, 1.65189418e-07, 1.46599607e-11, ...,
        2.03917976e-02, 2.63147096e-03, 4.29639278e-03],
       [2.67199359e-03, 1.12830161e-01, 4.72467848e-02, ...,
        9.15002171e-02, 2.72402107e-04, 2.43339970e-03],
       ...,
       [1.12028848e-02, 5.32201638e-01, 3.76167721e-01, ...,
        3.72233903e-02, 1.43557949e-02, 7.91787790e-03],
       [1.93421321e-01, 3.11689182e-04, 3.82596115e-04, ...,
        3.02871722e-04, 1.27418181e-02, 7.83094310e-01],
       [5.82605218e-03, 6.11344190e-01, 2.35314306e-01, ...,
        1.78215601e-02, 2.73559874e-02, 1.02707984e-02]])

In [16]:
log_loss(y_val, val_preds)

0.6402447786469354

In [17]:
log_loss(y_test, test_preds)

0.6327741030996542