In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2022-12-13T07:07:16.237713-05:00

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 7.28.0

Compiler    : GCC 9.3.0
OS          : Linux
Release     : 5.11.0-37-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 32
Architecture: 64bit



In [3]:
import numpy as np
import pandas as pd

In [4]:
%watermark --iversions

numpy : 1.22.4
pandas: 1.4.3



In [5]:
X_num_train = np.load('../input/otto_ii/X_num_train.npy')
X_num_val = np.load('../input/otto_ii/X_num_val.npy')
X_num_test = np.load('../input/otto_ii/X_num_test.npy')

y_train = np.load('../input/otto_ii/y_train.npy')
y_val = np.load('../input/otto_ii/y_val.npy')
y_test = np.load('../input/otto_ii/y_test.npy')

In [6]:
X_num_train.shape

(39601, 93)

In [7]:
X_num_train.size

3682893

In [8]:
index_nan = np.random.choice(X_num_train.size, X_num_train.shape[0]*2, replace=False)
index_nan

array([1755785, 2001970, 2685623, ...,  372306, 2219405, 1951943])

In [9]:
trains = []
for i in range(5):
    trains.append(X_num_train)

In [10]:
X_num_train_5 = np.vstack(trains)

In [11]:
X_num_train_5.shape

(198005, 93)

In [12]:
index_nan = np.random.choice(X_num_train_5.size, X_num_train_5.shape[0]*2, replace=False)
index_nan

array([7580070, 1183223, 6381474, ..., 1747376, 8814465, 3014003])

In [13]:
X_num_train_5.ravel()[index_nan] = np.nan

In [16]:
X_num_train_5[:5]

array([[ 5.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  4.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  4.,  0.,
         0.,  0.,  2.,  0.,  0.,  0.,  4.,  0.,  0.,  2.,  0., nan,  0.,
         0.,  3.,  2.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
         4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,  0., nan,
         1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
         3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,
         4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,
         0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,

In [17]:
columns = [f'Col{i}' for i in range(X_num_train.shape[1])]

In [18]:
X_num_train_5 = pd.DataFrame(X_num_train_5, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [19]:
y_train_5 = []
for i in range(5):
    y_train_5.append(y_train)

In [20]:
y_train_5 = np.hstack(y_train_5)

In [21]:
X_num_train_5.head()

Col0  Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  ...  Col83  \
0   5.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...    0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   NaN   0.0   0.0  ...    0.0   
2   2.0   0.0   0.0   0.0   0.0   NaN   0.0   0.0   0.0   0.0  ...    0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0  ...    0.0   

   Col84  Col85  Col86  Col87  Col88  Col89  Col90  Col91  Col92  
0    0.0    2.0    0.0    0.0    0.0    0.0    0.0    3.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    5.0    0.0    1.0    0.0    0.0    0.0    1.0    0.0  
3    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 93 columns]

In [22]:
X_num_train_5['target'] = y_train_5
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [23]:
X_num_train_5 = X_num_train_5.sample(frac=1).reset_index(drop=True)
X_num_train_5.head()

Col0  Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  ...  Col84  \
0   2.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
1   0.0   0.0   1.0   NaN   0.0   0.0   0.0   0.0   1.0   0.0  ...    1.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    1.0   
3   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...    3.0   
4   0.0   0.0  10.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   

   Col85  Col86  Col87  Col88  Col89  Col90  Col91  Col92  target  
0    3.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
1    0.0    5.0    0.0    0.0    0.0    NaN    0.0    1.0       8  
2    2.0    0.0    6.0    0.0    0.0    0.0    0.0    0.0       6  
3    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0       1  
4    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0       5  

[5 rows x 94 columns]

In [24]:
X_num_train_5 = X_num_train_5.sample(frac=1).reset_index(drop=True)
X_num_train_5.head()

Col0  Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  ...  Col84  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
1   0.0   0.0   6.0   9.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   0.0   0.0   0.0   1.0   2.0   0.0   0.0   0.0   2.0   0.0  ...    0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   NaN   3.0   0.0   0.0  ...    2.0   
4   2.0   0.0   2.0   1.0   0.0   0.0   2.0   0.0   0.0   0.0  ...    0.0   

   Col85  Col86  Col87  Col88  Col89  Col90  Col91  Col92  target  
0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0       2  
1    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0       5  
2    3.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0       5  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    2.0       6  

[5 rows x 94 columns]

In [25]:
X_num_train_5.to_csv('../input/otto_ii/xgtrain_5.csv', index=False)
X_num_val.to_csv('../input/otto_ii/xgval.csv', index=False)
X_num_test.to_csv('../input/otto_ii/xgtest.csv', index=False)