In [1]:
%load_ext watermark

In [2]:
%watermark

Last updated: 2022-12-16T09:13:23.851961-05:00

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 7.28.0

Compiler    : GCC 9.3.0
OS          : Linux
Release     : 5.11.0-37-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 32
Architecture: 64bit



In [3]:
import numpy as np
import pandas as pd

In [4]:
%watermark --iversions

pandas: 1.4.3
numpy : 1.22.4



In [5]:
X_num_train = np.load('../input/otto_ii/X_num_train.npy')
X_num_val = np.load('../input/otto_ii/X_num_val.npy')
X_num_test = np.load('../input/otto_ii/X_num_test.npy')

y_train = np.load('../input/otto_ii/y_train.npy')
y_val = np.load('../input/otto_ii/y_val.npy')
y_test = np.load('../input/otto_ii/y_test.npy')

In [6]:
X_num_train.shape

(39601, 93)

In [7]:
X_num_train.size

3682893

In [9]:
index_nan = np.random.choice(X_num_train.size, X_num_train.shape[0]*3, replace=False)
index_nan

array([1727158, 1207384,  158565, ..., 3231684,  970601, 1557886])

In [10]:
trains = []
for i in range(25):
    trains.append(X_num_train)

In [11]:
X_num_train_25 = np.vstack(trains)

In [11]:
X_num_train_25.shape

(990025, 93)

In [12]:
index_nan = np.random.choice(X_num_train_25.size, X_num_train_25.shape[0]*3, replace=False)
index_nan

array([11639979, 68852686, 32126211, ..., 72653246, 84842214, 91702641])

In [13]:
X_num_train_25.ravel()[index_nan] = np.nan

In [14]:
X_num_train_25[:5]

array([[ 5.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  4.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  4.,  0.,
         0.,  0.,  2.,  0.,  0.,  0.,  4.,  0.,  0.,  2.,  0.,  0.,  0.,
         0.,  3.,  2.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
         4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  1.,
         1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,
         1., nan,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
         3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,
         4.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  4.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0., nan,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,

In [15]:
columns = [f'Col{i}' for i in range(X_num_train.shape[1])]

In [16]:
X_num_train_25 = pd.DataFrame(X_num_train_25, columns=columns)
X_num_test = pd.DataFrame(X_num_test, columns=columns)
X_num_val = pd.DataFrame(X_num_val, columns=columns)

In [17]:
y_train_25 = []
for i in range(25):
    y_train_25.append(y_train)

In [18]:
y_train_25 = np.hstack(y_train_25)

In [19]:
X_num_train_25.head()

Col0  Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  ...  Col83  \
0   5.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...    0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   NaN  ...    0.0   
4   0.0   0.0   0.0   0.0   0.0   1.0   NaN   0.0   0.0   0.0  ...    0.0   

   Col84  Col85  Col86  Col87  Col88  Col89  Col90  Col91  Col92  
0    0.0    2.0    0.0    0.0    0.0    0.0    0.0    3.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    NaN    0.0    0.0  
2    NaN    5.0    0.0    1.0    0.0    0.0    0.0    1.0    0.0  
3    0.0    NaN    0.0    1.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 93 columns]

In [20]:
X_num_train_25['target'] = y_train_25
X_num_test['target'] = y_test
X_num_val['target'] = y_val

In [21]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

Col0  Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  ...  Col84  \
0   0.0   0.0   7.0   NaN   1.0   0.0   0.0   1.0   0.0   1.0  ...    0.0   
1   0.0   0.0   NaN   0.0   0.0   1.0   0.0   0.0   0.0   0.0  ...    0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  14.0   0.0  ...    0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  ...    0.0   
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0  ...    0.0   

   Col85  Col86  Col87  Col88  Col89  Col90  Col91  Col92  target  
0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0       5  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
2    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0       2  
3    0.0    0.0    0.0    1.0    0.0    0.0    1.0    0.0       8  
4    0.0    0.0    1.0    0.0    0.0    0.0    1.0    0.0       4  

[5 rows x 94 columns]

In [22]:
X_num_train_25 = X_num_train_25.sample(frac=1).reset_index(drop=True)
X_num_train_25.head()

Col0  Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  ...  Col84  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  13.0   2.0   0.0  ...    0.0   
1   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   2.0   0.0   6.0   2.0   0.0   0.0   0.0   1.0   0.0   7.0  ...    0.0   
3   1.0   1.0   7.0   3.0   0.0   0.0   1.0   0.0   0.0   1.0  ...    0.0   
4   5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  ...    0.0   

   Col85  Col86  Col87  Col88  Col89  Col90  Col91  Col92  target  
0    2.0    0.0    3.0    0.0    0.0    1.0    1.0    0.0       8  
1    2.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
2    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0       5  
3    0.0    0.0    NaN    1.0    0.0    0.0    0.0    0.0       5  
4    1.0    0.0    0.0    0.0    0.0    NaN    2.0    0.0       8  

[5 rows x 94 columns]

In [23]:
X_num_train_25.to_csv('../input/otto_ii/xgtrain_25_3XNaN.csv', index=False)
X_num_val.to_csv('../input/otto_ii/xgval.csv', index=False)
X_num_test.to_csv('../input/otto_ii/xgtest.csv', index=False)